### ISSUE TITLE
Issue: I can't sign in! 

### ISSUE THREAD

**Issue by Zafaryor1** [vishalanandl177/Realtime-Quiz-Android-App#1]
Hi developer. I can't sign in. Why?

**Comment by Zafaryor1** [comment]
![Screenshot_20200312-220705](https://user-images.githubusercontent.com/62112830/76546767-f872fc00-6483-11ea-9d55-734930d29b76.png)
Here is it.

**Comment by vishalanandl177** [comment]
Sorry about that Zafar.
The Firebase app is no longer available. So please create an app in your Firebase account and link the app. Don't know how?
Search for Firebase codelab friendly chat. This application is based on that.
